### ISSUE TITLE
Create unit tests asap.

### ISSUE THREAD

**Issue by aykut** [aykut/django-bulk-update#6]

**Comment by nueverest** [comment]
yes please

**Comment by towr** [comment]
I've made a pull-request with a testscript and two testcases. And I've added a travis-ci config which, unfortunately, I haven't been able to test yet.

The main question is what do we want to test?
environments: [python 2,7, python 3.4] x [sqlite, mysql, postgresql] x [django-1.7 , ??]
tests: basic usage (test exists), update_fields, exclude_fields, every type of django field?? (since casting has been an issue), batch_size?, what else?

**Comment by aykut** [comment]
Thanks for this great work.

We could also add django-1.6 to environments. It would be great to add a test for every type of django field. However this would be a lot of work for single person, I can help you with this. I'll try to add more test cases today.

Besides, I can't run the tests with django-1.6, I'll investigate it.

**Comment by towr** [comment]
I've update the runtest-script so it's django 1.6 compatible. It passes the test for django 1.6 now as well.
